# Generated by Django 4.1.5 on 2023-02-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GithubUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('total_followers', models.PositiveIntegerField()),
                ('bio', models.CharField(max_length=500)),
                ('total_publicrepos', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=500)),
            ],
        ),
    ]
