# Generated by Django 4.1.6 on 2023-02-01 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0002_repository'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubuser',
            name='total_followers',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='total_publicrepos',
            field=models.IntegerField(),
        ),
    ]
