# Generated by Django 4.1.6 on 2023-02-01 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0003_alter_githubuser_total_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubuser',
            name='bio',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='location',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
