# Generated by Django 4.1.6 on 2023-02-02 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0004_alter_githubuser_bio_alter_githubuser_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubuser',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='username',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
