# Generated by Django 4.1.6 on 2023-02-02 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0005_alter_githubuser_bio_alter_githubuser_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='owner',
            new_name='githubuser',
        ),
    ]
